version: '3.1'

services:

  postgres:
    image: postgres:16.1
    restart: no
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: patata
      POSTGRES_DB: userdb
      PDDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

volumes:
  postgres_volume: