version: '3.1'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tgtsAXhC77nTjifT
      MYSQL_DATABASE: 2dd07_my
      MYSQL_USER: 2dd07
      MYSQL_PASSWORD: tgtsAXhC77nTjifT
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: tgtsAXhC77nTjifT
    depends_on:
      - db

volumes:
  db-data:
